[project]
name = "bergen_bikeshare_app"
version = "0.1.0"
dependencies = [
    "pytest == 9.0.3",
    "pytest-cov == 7.1.0",
    "ruff == 0.15.16",
    "shiny == 1.6.3",
    "faker == 40.23.0"
]
requires-python = ">= 3.13"
authors = [{ name = "Sunniva Nord Bjerga", email = "sunnivanordbjerga@gmail.com" }]
maintainers = [{ name = "Sunniva Nord Bjerga", email = "sunnivanordbjerga@gmail.com" }]
description = "Administrator dashboard for a fictional bikeshare company."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["bike", "bikeshare", "bergen", "shiny", "database", "dashboard"]

[project.urls]
Repository = "https://github.com/sunnivanordbjerga/bergen-bikeshare-app"

[tool.pytest.ini_options]
pythonpath = ["src"]
